SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 1 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 1 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 1 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 1 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 1 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 2 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 2 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 2 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 2 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 2 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 3 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 3 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 3 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 3 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 3 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 4 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 4 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 4 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 4 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 4 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 5 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 5 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 5 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 5 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 5 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 6 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 6 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 6 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 6 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 6 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 7 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 7 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 7 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 7 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 7 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 8 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 8 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 8 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 8 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 8 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 9 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 9 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 9 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 9 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 9 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 10 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 10 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 10 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 10 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 10 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 11 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 11 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 11 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 11 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 11 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 12 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 12 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 12 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 12 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2015 AND pu_month = 12 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 1 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 1 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 1 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 1 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 1 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 2 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 2 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 2 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 2 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 2 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 3 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 3 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 3 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 3 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 3 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 4 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 4 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 4 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 4 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 4 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 5 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 5 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 5 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 5 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 5 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 6 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 6 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 6 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 6 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 6 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 7 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 7 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 7 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 7 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 7 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 8 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 8 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 8 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 8 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 8 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 9 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 9 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 9 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 9 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 9 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 10 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 10 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 10 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 10 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 10 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 11 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 11 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 11 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 11 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 11 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 12 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 12 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 12 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 12 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2016 AND pu_month = 12 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 1 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 1 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 1 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 1 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 1 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 2 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 2 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 2 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 2 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 2 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 3 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 3 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 3 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 3 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 3 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 4 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 4 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 4 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 4 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 4 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 5 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 5 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 5 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 5 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 5 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 6 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 6 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 6 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 6 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 6 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 7 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 7 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 7 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 7 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 7 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 8 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 8 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 8 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 8 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 8 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 9 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 9 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 9 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 9 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 9 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 10 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 10 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 10 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 10 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 10 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 11 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 11 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 11 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 11 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 11 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 12 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 12 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 12 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 12 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2017 AND pu_month = 12 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 1 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 1 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 1 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 1 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 1 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 2 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 2 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 2 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 2 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 2 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 3 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 3 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 3 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 3 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 3 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 4 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 4 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 4 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 4 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 4 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 5 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 5 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 5 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 5 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 5 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 6 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 6 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 6 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 6 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 6 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 7 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 7 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 7 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 7 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 7 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 8 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 8 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 8 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 8 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 8 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 9 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 9 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 9 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 9 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 9 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 10 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 10 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 10 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 10 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 10 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 11 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 11 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 11 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 11 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 11 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 12 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 12 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 12 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 12 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2018 AND pu_month = 12 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 1 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 1 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 1 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 1 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 1 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 2 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 2 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 2 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 2 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 2 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 3 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 3 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 3 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 3 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 3 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 4 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 4 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 4 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 4 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 4 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 5 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 5 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 5 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 5 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 5 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 6 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 6 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 6 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 6 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 6 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 7 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 7 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 7 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 7 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 7 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 8 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 8 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 8 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 8 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 8 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 9 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 9 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 9 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 9 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 9 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 10 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 10 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 10 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 10 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 10 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 11 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 11 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 11 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 11 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 11 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 12 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 12 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 12 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 12 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2019 AND pu_month = 12 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 1 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 1 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 1 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 1 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 1 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 2 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 2 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 2 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 2 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 2 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 3 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 3 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 3 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 3 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 3 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 4 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 4 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 4 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 4 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 4 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 5 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 5 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 5 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 5 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 5 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 6 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 6 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 6 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 6 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 6 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 7 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 7 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 7 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 7 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 7 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 8 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 8 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 8 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 8 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 8 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 9 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 9 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 9 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 9 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 9 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 10 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 10 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 10 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 10 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 10 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 11 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 11 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 11 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 11 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 11 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 12 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 12 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 12 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 12 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2020 AND pu_month = 12 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 1 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 1 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 1 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 1 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 1 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 2 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 2 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 2 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 2 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 2 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 3 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 3 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 3 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 3 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 3 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 4 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 4 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 4 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 4 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 4 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 5 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 5 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 5 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 5 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 5 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 6 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 6 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 6 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 6 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 6 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 7 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 7 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 7 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 7 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 7 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 8 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 8 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 8 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 8 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 8 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 9 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 9 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 9 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 9 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 9 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 10 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 10 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 10 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 10 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 10 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 11 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 11 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 11 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 11 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 11 AND day_period = 'Late Night'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 12 AND day_period = 'Morning'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 12 AND day_period = 'Afternoon'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 12 AND day_period = 'Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 12 AND day_period = 'Late Evening'; 
SELECT COUNT(*) FROM yellow_taxi WHERE pu_year = 2021 AND pu_month = 12 AND day_period = 'Late Night'; 
